name: CI
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  distribution: "adopt"
                  java-version: "17"

            - name: Install dependencies
              run: sudo apt install build-essential gcc g++ cmake make ninja-build git wget openssl zipalign apksigner zip unzip openjdk-19-jre-headless -y

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
              with:
                  cmdline-tools-version: 8512546

            - name: Setup NDK r23c
              run: |
                  curl -o r23c.zip https://dl.google.com/android/repository/android-ndk-r23c-linux.zip
                  unzip r23c.zip -d $HOME

            #             - name: Setup Android NDK
            #               uses: nttld/setup-ndk@v1
            #               id: setup-ndk
            #               with:
            #                   ndk-version: r23c
            #                   link-to-sdk: true

            - name: Checkout submodules
              run: git submodule update --init --recursive
              shell: bash

            - name: Build libemucore
              run: |
                  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk-r23c/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-26 -DANDROID_ABI=arm64-v8a 
                  make -j8

            - name: Create android build with shell apk
              run: |
                  mkdir -p apk/lib/arm64-v8a
                  curl -L -o apk/purplesx2.apk https://github.com/mininxd/AetherSX2-reborn/releases/download/shell/shell
                  cp pcsx2/libemucore.so apk/lib/arm64-v8a/
                  cd apk
                  zip -0 purplesx2.apk lib/arm64-v8a/libemucore.so
                  zipalign -p 4 purplesx2.apk purplesx2-aligned.apk
                  curl -L https://github.com/tytydraco/public-keystore/raw/main/public.jks -o public.jks
                  apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
                  "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in ./purplesx2-aligned.apk --out ./purplesx2-signed.apk
              shell: bash

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: shell-apk
                  path: ./apk/purplesx2-signed.apk
